# Worksheet 05

Name:  Sangheon Jeong
UID: U72771619

### Topics

- Cost Functions
- Kmeans

### Cost Function

Solving Data Science problems often starts by defining a metric with which to evaluate solutions were you able to find some. This metric is called a cost function. Data Science then backtracks and tries to find a process / algorithm to find solutions that can optimize for that cost function.

For example suppose you are asked to cluster three points A, B, C into two non-empty clusters. If someone gave you the solution `{A, B}, {C}`, how would you evaluate that this is a good solution?

Notice that because the clusters need to be non-empty and all points must be assigned to a cluster, it must be that two of the three points will be together in one cluster and the third will be alone in the other cluster.

In the above solution, if A and B are closer than A and C, and B and C, then this is a good solution. The smaller the distance between the two points in the same cluster (here A and B), the better the solution. So we can define our cost function to be that distance (between A and B here)!

The algorithm / process would involve clustering together the two closest points and put the third in its own cluster. This process optimizes for that cost function because no other pair of points could have a lower distance (although it could equal it).

### K means

a) (1-dimensional clustering) Walk through Lloyd's algorithm step by step on the following dataset:

`[0, .5, 1.5, 2, 6, 6.5, 7]` (note: each of these are 1-dimensional data points)

Given the initial centroids:

`[0, 2]`

[0, .5][1.5, 2, 6, 6.5, 7]

[0.25, 4.6]


[0, .5, 1.5, 2][6, 6.5, 7]

[1, 6.5]


#Converge

[0, .5, 1.5, 2][6, 6.5, 7]

[1, 6.5]

b) Describe in plain english what the cost function for k means is.

The sum of squared distances of each data point to it's assigned cluster centriod.

c) For the same number of clusters K, why could there be very different solutions to the K means algorithm on a given dataset?

It is because there are multiple factors that determine the result such as initial centroids, local minima, or sensitivity of outliers.

d) Does Lloyd's Algorithm always converge? Why / why not?

Lloyd's Algorithm will always converge to the local minimum. It is because the algorithm is a greedy algorithm that keeps decreasing the value of objective function 

e) Follow along in class the implementation of Kmeans

In [5]:
import numpy as np
from PIL import Image as im
import matplotlib.pyplot as plt
import sklearn.datasets as datasets

centers = [[0, 0], [2, 2], [-3, 2], [2, -4]]
X, _ = datasets.make_blobs(n_samples=300, centers=centers, cluster_std=1, random_state=0)

class KMeans():

    def __init__(self, data, k):
        self.data = data
        self.k = k
        self.assignment = [-1 for _ in range(len(data))]
        self.snaps = []
    
    def snap(self, centers):
        TEMPFILE = "temp.png"

        fig, ax = plt.subplots()
        ax.scatter(X[:, 0], X[:, 1], c=self.assignment)
        ax.scatter(centers[:,0], centers[:, 1], c='r')
        fig.savefig(TEMPFILE)
        plt.close()
        self.snaps.append(im.fromarray(np.asarray(im.open(TEMPFILE))))
        
    def is_unassigned(self, i):
        return self.assignment[i] == -1
    
    def unassign_all(self):
        self.assignment = [-1 for _ in range(len(self.data))]
        
    def initialize(self):
        return self.data[np.random.choice(range(len(self.data)), size=self.k, replace=False)]
    
    def are_centers_diff(self, c1, c2):
        for i in range(len(c1)):
            if c1[i] not in c2:
                return True
        return False
    
    def assign(self, centers):
        for i in range(len(self.data)):
            self.assignment[i] = 0
            temp_assign = 0
            temp_dist = self.dist(self.data[i], centers[0])
            for j in range(1, len(centers)):
                new_dist = self.dist(self.data[i], centers[j])
                if temp_dist > new_dist:
                    self.assignment[i] = j
                    temp_dist = new_dist
    
    def calculate_new_centers(self):
        centers = []
        for j in range(self.k):
            cluster_j = self.data[
                np.array([i for i in range(len(self.data)) if self.assignment[i] == j])
            ]
            centers.append(np.mean(cluster_j,axis=0))
        
        return np.array(centers)

    def dist(self, x, y):
        return sum((x - y) ** 2) ** (1/2)

    def lloyds(self):
        centers = self.initialize()
        self.assign(centers)
        self.snap(centers)
        new_centers = self.calculate_new_centers()
        while self.are_centers_diff(centers, new_centers):
            centers = new_centers
            self.snap(centers)
            self.unassign_all()
            self.assign(centers)
            new_centers = self.calculate_new_centers()
            print (new_centers)
        return
            
kmeans = KMeans(X, 4)
kmeans.lloyds()
images = kmeans.snaps

images[0].save(
    'kmeans.gif',
    optimize=False,
    save_all=True,
    append_images=images[1:],
    loop=0,
    duration=500
)

[[ 1.3558419   1.81502838]
 [ 3.21643471  1.85730826]
 [ 1.54641984 -3.315869  ]
 [-2.36915637  1.40919497]]
[[ 0.99697562  1.38656027]
 [ 2.9901294   1.93033116]
 [ 1.6846506  -3.71223524]
 [-2.58106162  1.44753177]]
[[ 0.73198734  0.95193618]
 [ 2.73113397  2.13615305]
 [ 1.74967041 -3.91342476]
 [-2.77494761  1.60122779]]
[[ 0.45700867  0.61653274]
 [ 2.42163747  2.16625408]
 [ 1.80681264 -4.00628273]
 [-2.92333071  1.72126447]]
[[ 0.23522051  0.30468359]
 [ 2.15336348  2.13122896]
 [ 1.84585117 -4.10098602]
 [-3.02637537  1.78522568]]
[[ 0.07901472  0.12374048]
 [ 1.99675063  2.08534384]
 [ 1.84585117 -4.10098602]
 [-3.07703402  1.85266958]]
[[ 0.01314837  0.04525929]
 [ 1.93298349  2.03064159]
 [ 1.84585117 -4.10098602]
 [-3.07703402  1.85266958]]
[[ 0.00522174  0.0246759 ]
 [ 1.91535954  2.02383689]
 [ 1.84585117 -4.10098602]
 [-3.07703402  1.85266958]]
[[ 0.00522174  0.0246759 ]
 [ 1.91535954  2.02383689]
 [ 1.84585117 -4.10098602]
 [-3.07703402  1.85266958]]
